wireplumber.settings = {
  device.restore-profile = false
  node.restore-default-targets = false
}

monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.pci-0000_05_00.0"
      }
    ]
    actions = {
      update-props = {
        session.dont-restore-off-profile = true
      }
    }
  }
]

device.profile.priority.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.pci-0000_05_00.0"
      }
    ]
    actions = {
      update-props = {
        priorities = [ "pro-audio", "output:hdmi-stereo-extra1" ]
      }
    }
  }
]
